run: train+predict
data:
    data_root_dir: data
    num_workers: 5
    image_feat_train :
      - rcnn_10_100/train2014
      - rcnn_10_100/val2014
    imdb_file_train :
      - imdb/imdb_train2014.npy
      - imdb/imdb_val2014.npy
