data:
  data_root_dir: data
  image_feat_test:
  - detectron_23/fc6/test2015
  image_feat_train:
  - detectron_23/fc6/train2014
  - detectron_23/fc6/val2014
  image_feat_val:
  - detectron_23/fc6/val2014
  image_max_loc: 100
  imdb_file_test:
  - imdb/imdb_test2015.npy
  imdb_file_train:
  - imdb/imdb_train2014.npy
  - imdb/imdb_val2014.npy
  imdb_file_val:
  - imdb/imdb_minival2014.npy
model:
  image_feature_encoding:
  - method: finetune_faster_rcnn_fpn_fc7
    par:
      weights_file: detectron_23/fc6/fc7_w.pkl
      bias_file: detectron_23/fc6/fc7_b.pkl
